cache:
  paths:
    - .m2/repository

build:
  image: maven:3-jdk-8
  script: mvn clean package && mv target/Zuul-*.jar
  artifacts:
    name: "Zuul"
    paths:
      - Zuul-*.jar

pages:
  image: maven:3-jdk-8
  script:
    - sh doc.sh
    - mkdir .public
    - cp -r progdoc .public/
    - cp -r userdoc .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master